"""Physical Spanish naming contract for SQLite.

Python attributes intentionally remain in English. ``key`` preserves those
attribute names for SQLAlchemy expressions while ``name`` is the physical
SQLite identifier.
"""

from typing import Any

from sqlalchemy.orm import mapped_column


TABLE_NAMES = {
    "audit_events": "eventos_auditoria",
    "authorizations": "autorizaciones",
    "business_settings": "configuracion_negocio",
    "cash_expenses": "gastos_caja",
    "cash_shifts": "cortes_caja",
    "command_batches": "lotes_comanda",
    "dining_tables": "mesas",
    "employee_roles": "roles_empleado",
    "employees": "empleados",
    "folio_sequences": "secuencias_folio",
    "inventory_items": "insumos_inventario",
    "inventory_movements": "movimientos_inventario",
    "menu_categories": "categorias_menu",
    "payment_methods": "metodos_pago",
    "payments": "pagos",
    "permissions": "permisos",
    "pos_devices": "dispositivos_pos",
    "pos_sessions": "sesiones_pos",
    "print_jobs": "trabajos_impresion",
    "printers": "impresoras",
    "product_package_items": "componentes_paquete_producto",
    "product_packages": "paquetes_producto",
    "product_recipes": "recetas_producto",
    "product_station_assignments": "asignaciones_estacion_producto",
    "production_stations": "estaciones_produccion",
    "products": "productos",
    "purchase_receipt_lines": "lineas_recepcion_compra",
    "purchase_receipts": "recepciones_compra",
    "role_permissions": "permisos_rol",
    "roles": "roles",
    "service_zones": "zonas_servicio",
    "station_order_lines": "lineas_orden_estacion",
    "station_orders": "ordenes_estacion",
    "stock_alerts": "alertas_stock",
    "sync_inbox": "bandeja_entrada_sincronizacion",
    "sync_outbox": "bandeja_salida_sincronizacion",
    "sync_watermarks": "marcas_agua_sincronizacion",
    "table_status_events": "eventos_estado_mesa",
    "ticket_discounts": "descuentos_ticket",
    "ticket_line_notes": "notas_linea_ticket",
    "ticket_line_modifications": "modificaciones_linea_ticket",
    "ticket_lines": "lineas_ticket",
    "tickets": "tickets",
    "unit_conversions": "conversiones_unidad",
    "units": "unidades",
}

_COLUMN_OVERRIDES = {
    "id": "id",
    "sku": "sku",
    "pos_alias": "alias_pos",
    "timezone": "zona_horaria",
    "airtable_record_id": "airtable_registro_id",
    "payload_json": "contenido_json",
    "before_snapshot": "instantanea_antes",
    "after_snapshot": "instantanea_despues",
    "content_snapshot": "instantanea_contenido",
    "printer_key_snapshot": "clave_impresora_instantanea",
    "product_name_snapshot": "nombre_producto_instantanea",
    "product_sku_snapshot": "sku_producto_instantanea",
    "category_id_snapshot": "categoria_id_instantanea",
    "station_id_snapshot": "estacion_id_instantanea",
    "note_snapshot": "nota_instantanea",
    "status_cache": "estado_temporal",
    "sync_status": "estado_sincronizacion",
    "waste_pct": "porcentaje_merma",
    "paper_width_mm": "ancho_papel_mm",
    "tax_enabled": "impuestos_activos",
    "tax_rate_bps": "tasa_impuesto_bps",
    "tax_included": "impuesto_incluido",
    "tax_label": "etiqueta_impuesto",
    "percent_bps": "porcentaje_bps",
}

_WORDS = {
    "id": "id",
    "pos": "pos",
    "allocation": "asignacion",
    "override": "reemplazo",
    "on": "en",
    "customer": "cliente",
    "recipe": "receta",
    "action": "accion",
    "consumed": "consumido",
    "payload": "contenido",
    "primary": "principal",
    "qty": "cantidad",
    "retry": "reintento",
    "shift": "corte",
    "snapshot": "instantanea",
    "stock": "stock",
    "accepted": "aceptacion",
    "acknowledged": "reconocimiento",
    "active": "activo",
    "actor": "actor",
    "after": "despues",
    "aggregate": "agregado",
    "alert": "alerta",
    "amount": "importe",
    "applied": "aplicacion",
    "attempts": "intentos",
    "authorization": "autorizacion",
    "authorized": "autorizado",
    "autocut": "autocorte",
    "average": "promedio",
    "base": "base",
    "batch": "lote",
    "before": "antes",
    "behavior": "comportamiento",
    "billing": "cobro",
    "business": "negocio",
    "buzzer": "localizador",
    "cancel": "cancelacion",
    "cancelled": "cancelacion",
    "captured": "capturada",
    "card": "tarjeta",
    "cash": "caja",
    "cashier": "cajero",
    "category": "categoria",
    "change": "cambio",
    "claimed": "toma",
    "closed": "cierre",
    "closing": "cierre",
    "code": "codigo",
    "command": "comanda",
    "component": "componente",
    "connection": "conexion",
    "content": "contenido",
    "converted": "convertida",
    "completed": "terminacion",
    "created": "creacion",
    "creator": "creador",
    "currency": "moneda",
    "courtesy": "cortesia",
    "current": "actual",
    "declared": "declarado",
    "delivered": "entrega",
    "description": "descripcion",
    "device": "dispositivo",
    "difference": "diferencia",
    "discount": "descuento",
    "display": "visualizacion",
    "employee": "empleado",
    "enabled": "habilitado",
    "entity": "entidad",
    "error": "error",
    "event": "evento",
    "expected": "esperado",
    "expense": "gasto",
    "expenses": "gastos",
    "factor": "factor",
    "failed": "fallo",
    "family": "familia",
    "finished": "terminacion",
    "folio": "folio",
    "from": "origen",
    "full": "completo",
    "guest": "comensales",
    "idempotency": "idempotencia",
    "image": "imagen",
    "inventory": "inventario",
    "included": "incluido",
    "invoice": "factura",
    "is": "es",
    "item": "insumo",
    "job": "trabajo",
    "key": "clave",
    "label": "etiqueta",
    "last": "ultimo",
    "line": "linea",
    "location": "ubicacion",
    "logo": "logotipo",
    "message": "mensaje",
    "method": "metodo",
    "minimum": "minimo",
    "mode": "modo",
    "movement": "movimiento",
    "name": "nombre",
    "net": "neto",
    "next": "siguiente",
    "note": "nota",
    "notes": "notas",
    "number": "numero",
    "opened": "apertura",
    "opening": "apertura",
    "order": "orden",
    "package": "paquete",
    "padding": "relleno",
    "paid": "pago",
    "parent": "padre",
    "password": "contrasena",
    "payment": "pago",
    "permission": "permiso",
    "prefix": "prefijo",
    "price": "precio",
    "print": "impresion",
    "printed": "impresion",
    "printer": "impresora",
    "processed": "procesamiento",
    "product": "producto",
    "promotion": "promocion",
    "pulled": "descarga",
    "purchase": "compra",
    "quantity": "cantidad",
    "reason": "motivo",
    "rate": "tasa",
    "receipt": "recepcion",
    "received": "recepcion",
    "reference": "referencia",
    "registered": "registrado",
    "remote": "remoto",
    "requested": "solicitado",
    "requires": "requiere",
    "resolved": "resolucion",
    "revision": "revision",
    "role": "rol",
    "round": "ronda",
    "sales": "ventas",
    "sent": "envio",
    "sequence": "secuencia",
    "signed": "con_signo",
    "sort": "orden",
    "source": "origen",
    "started": "inicio",
    "station": "estacion",
    "status": "estado",
    "subtotal": "subtotal",
    "supplier": "proveedor",
    "sync": "sync",
    "table": "mesa",
    "target": "objetivo",
    "tax": "impuesto",
    "threshold": "umbral",
    "ticket": "ticket",
    "to": "destino",
    "total": "total",
    "transfer": "transferencia",
    "type": "tipo",
    "unit": "unidad",
    "updated": "actualizacion",
    "variant": "variante",
    "version": "version",
    "visible": "visible",
    "waiter": "mesero",
    "watermark": "marca_agua",
    "zone": "zona",
    "at": "fecha",
    "by": "por",
    "count": "conteo",
    "cost": "costo",
    "cents": "centavos",
    "pct": "porcentaje",
    "ref": "referencia",
    "path": "ruta",
    "width": "ancho",
    "mm": "mm",
    "json": "json",
    "airtable": "airtable",
    "record": "registro",
    "cursor": "cursor",
    "successful": "exitosa",
    "pull": "descarga",
    "push": "envio",
    "inbox": "entrada",
    "outbox": "salida",
}


def physical_table_name(python_name: str) -> str:
    return TABLE_NAMES[python_name]


def physical_column_name(attribute_name: str) -> str:
    if attribute_name in _COLUMN_OVERRIDES:
        return _COLUMN_OVERRIDES[attribute_name]
    try:
        return "_".join(_WORDS[word] for word in attribute_name.split("_"))
    except KeyError as exc:  # fail at model import instead of leaking an English name
        raise KeyError(
            f"No Spanish column mapping for {attribute_name!r}: {exc.args[0]}"
        ) from exc


def db_column(attribute_name: str, *args: Any, **kwargs: Any):
    """Build a mapped column with a Spanish physical name and English ORM key."""
    return mapped_column(
        physical_column_name(attribute_name), *args, key=attribute_name, **kwargs
    )
