"""create inventory operation schema

Revision ID: aec316b102f0
Revises: f70a38dc3ffc
Create Date: 2026-06-19 17:36:42.090953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec316b102f0'
down_revision: Union[str, Sequence[str], None] = 'f70a38dc3ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_unit_id', sa.Integer(), nullable=False),
    sa.Column('to_unit_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['to_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_unit_id', 'to_unit_id', name='uq_unit_conversion_pair')
    )
    op.create_table('stock_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('cash_shift_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('cash_expense_id', sa.Integer(), nullable=True),
    sa.Column('receipt_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invoice_note', sa.Text(), nullable=True),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_expense_id'], ['cash_expenses.id'], ),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['registered_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('purchase_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_receipt_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('captured_quantity', sa.Integer(), nullable=False),
    sa.Column('captured_unit_id', sa.Integer(), nullable=False),
    sa.Column('converted_quantity_base', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_receipt_id'], ['purchase_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=64), nullable=False),
    sa.Column('quantity_base', sa.Integer(), nullable=False),
    sa.Column('signed_quantity_base', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents_snapshot', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('ticket_line_id', sa.Integer(), nullable=True),
    sa.Column('purchase_receipt_line_id', sa.Integer(), nullable=True),
    sa.Column('cash_expense_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_expense_id'], ['cash_expenses.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['purchase_receipt_line_id'], ['purchase_receipt_lines.id'], ),
    sa.ForeignKeyConstraint(['registered_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['ticket_line_id'], ['ticket_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_movements')
    op.drop_table('purchase_receipt_lines')
    op.drop_table('purchase_receipts')
    op.drop_table('stock_alerts')
    op.drop_table('unit_conversions')
    # ### end Alembic commands ###
