"""create catalog and sync base schema

Revision ID: f5e60c69c395
Revises: 
Create Date: 2026-06-19 17:27:45.775838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e60c69c395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('pos_alias', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('permission_key')
    )
    op.create_table('production_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('printer_key', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('station_key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('role_key')
    )
    op.create_table('sync_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=False),
    sa.Column('remote_revision', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'airtable_record_id', 'remote_revision', name='uq_sync_inbox_remote_revision')
    )
    op.create_table('sync_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload_version', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_sync_outbox_event_id')
    )
    op.create_table('sync_watermarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('last_successful_pull_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_push_at', sa.DateTime(), nullable=True),
    sa.Column('last_remote_cursor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', name='uq_sync_watermark_entity_type')
    )
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('unit_family', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('unit_key')
    )
    op.create_table('employee_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'role_id', name='uq_employee_role')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('base_unit_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('minimum_stock_qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('item_code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('variant', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=220), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('visible_pos', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('product_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_product_id', sa.Integer(), nullable=False),
    sa.Column('package_mode', sa.String(length=64), nullable=False),
    sa.Column('print_behavior', sa.String(length=64), nullable=False),
    sa.Column('inventory_behavior', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('package_product_id')
    )
    op.create_table('product_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_base', sa.Integer(), nullable=False),
    sa.Column('waste_pct', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('product_id', 'inventory_item_id', name='uq_product_inventory_recipe')
    )
    op.create_table('product_station_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('product_id', 'station_id', name='uq_product_station_assignment')
    )
    op.create_table('product_package_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('station_id_override', sa.Integer(), nullable=True),
    sa.Column('price_allocation_cents', sa.Integer(), nullable=True),
    sa.Column('visible_on_customer_ticket', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('remote_revision', sa.String(length=128), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['product_packages.id'], ),
    sa.ForeignKeyConstraint(['station_id_override'], ['production_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airtable_record_id'),
    sa.UniqueConstraint('package_id', 'component_product_id', name='uq_package_component')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_package_items')
    op.drop_table('product_station_assignments')
    op.drop_table('product_recipes')
    op.drop_table('product_packages')
    op.drop_table('role_permissions')
    op.drop_table('products')
    op.drop_table('inventory_items')
    op.drop_table('employee_roles')
    op.drop_table('units')
    op.drop_table('sync_watermarks')
    op.drop_table('sync_outbox')
    op.drop_table('sync_inbox')
    op.drop_table('roles')
    op.drop_table('production_stations')
    op.drop_table('permissions')
    op.drop_table('menu_categories')
    op.drop_table('employees')
    # ### end Alembic commands ###
