"""create operation pos schema

Revision ID: f70a38dc3ffc
Revises: f5e60c69c395
Create Date: 2026-06-19 17:33:55.606313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70a38dc3ffc'
down_revision: Union[str, Sequence[str], None] = 'f5e60c69c395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=160), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('ticket_message', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('inventory_enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folio_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_key', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_key', name='uq_folio_sequence_key')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('requires_reference', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method_key', name='uq_payment_method_key')
    )
    op.create_table('pos_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('location_label', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_key', name='uq_service_zone_key')
    )
    op.create_table('authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('authorized_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requested_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opening_cash_cents', sa.Integer(), nullable=False),
    sa.Column('declared_cash_cents', sa.Integer(), nullable=True),
    sa.Column('expected_cash_cents', sa.Integer(), nullable=True),
    sa.Column('sales_total_cents', sa.Integer(), nullable=False),
    sa.Column('cash_total_cents', sa.Integer(), nullable=False),
    sa.Column('card_total_cents', sa.Integer(), nullable=False),
    sa.Column('transfer_total_cents', sa.Integer(), nullable=False),
    sa.Column('expenses_total_cents', sa.Integer(), nullable=False),
    sa.Column('net_total_cents', sa.Integer(), nullable=False),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('average_ticket_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['opened_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('dining_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_code', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('buzzer_number', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status_cache', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['service_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_code', name='uq_dining_table_code')
    )
    op.create_table('pos_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['pos_devices.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('paper_width_mm', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('connection_ref', sa.String(length=255), nullable=True),
    sa.Column('autocut_enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printer_key', name='uq_printer_key')
    )
    op.create_table('cash_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('cash_shift_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('expense_type', sa.String(length=32), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('registered_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('authorized_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['registered_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('cash_shift_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('waiter_employee_id', sa.Integer(), nullable=True),
    sa.Column('closed_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('billing_started_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ),
    sa.ForeignKeyConstraint(['closed_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['opened_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['dining_tables.id'], ),
    sa.ForeignKeyConstraint(['waiter_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('actor_employee_id', sa.Integer(), nullable=True),
    sa.Column('cash_shift_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('before_snapshot', sa.Text(), nullable=True),
    sa.Column('after_snapshot', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(length=32), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'round_number', 'batch_type', name='uq_command_batch_round_type')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('cash_shift_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('cashier_employee_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('received_cents', sa.Integer(), nullable=True),
    sa.Column('change_cents', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cancelled_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ),
    sa.ForeignKeyConstraint(['cashier_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('table_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('actor_employee_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['dining_tables.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('discount_source', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('authorized_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_batch_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['command_batch_id'], ['command_batches.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('ticket_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('parent_ticket_line_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('package_item_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.Column('price_mode', sa.String(length=32), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=220), nullable=False),
    sa.Column('product_sku_snapshot', sa.String(length=80), nullable=True),
    sa.Column('category_id_snapshot', sa.Integer(), nullable=True),
    sa.Column('station_id_snapshot', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('cancel_authorized_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancel_authorized_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['product_packages.id'], ),
    sa.ForeignKeyConstraint(['package_item_id'], ['product_package_items.id'], ),
    sa.ForeignKeyConstraint(['parent_ticket_line_id'], ['ticket_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('printer_key_snapshot', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('cash_shift_id', sa.Integer(), nullable=True),
    sa.Column('station_order_id', sa.Integer(), nullable=True),
    sa.Column('command_batch_id', sa.Integer(), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shifts.id'], ),
    sa.ForeignKeyConstraint(['command_batch_id'], ['command_batches.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['station_order_id'], ['station_orders.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio'),
    sa.UniqueConstraint('idempotency_key', name='uq_print_job_idempotency_key')
    )
    op.create_table('station_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_order_id', sa.Integer(), nullable=False),
    sa.Column('ticket_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=220), nullable=False),
    sa.Column('note_snapshot', sa.Text(), nullable=True),
    sa.Column('line_action', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['station_order_id'], ['station_orders.id'], ),
    sa.ForeignKeyConstraint(['ticket_line_id'], ['ticket_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_line_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_line_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['ticket_line_id'], ['ticket_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_line_notes')
    op.drop_table('station_order_lines')
    op.drop_table('print_jobs')
    op.drop_table('ticket_lines')
    op.drop_table('station_orders')
    op.drop_table('ticket_discounts')
    op.drop_table('table_status_events')
    op.drop_table('payments')
    op.drop_table('command_batches')
    op.drop_table('audit_events')
    op.drop_table('tickets')
    op.drop_table('cash_expenses')
    op.drop_table('printers')
    op.drop_table('pos_sessions')
    op.drop_table('dining_tables')
    op.drop_table('cash_shifts')
    op.drop_table('authorizations')
    op.drop_table('service_zones')
    op.drop_table('pos_devices')
    op.drop_table('payment_methods')
    op.drop_table('folio_sequences')
    op.drop_table('business_settings')
    # ### end Alembic commands ###
