import { useState, type FormEvent } from "react";
import { X } from "lucide-react";
import { BrutalButton } from "../../../shared/components/BrutalButton";
import type { TicketLine } from "../../tickets/types/ticketTypes";
import { SplitLineSelector } from "./SplitLineSelector";

type Props = { lines: TicketLine[]; usedIds: Set<number>; allowEqual: boolean; isSaving: boolean; errorMessage: string | null; onClose: () => void; onEqual: (parts: number) => void; onLines: (name: string, lineIds: number[]) => void };
export function SplitTicketDialog({ lines, usedIds, allowEqual, isSaving, errorMessage, onClose, onEqual, onLines }: Props) {
  const [mode, setMode] = useState<"equal" | "lines">(allowEqual ? "equal" : "lines");
  const [parts, setParts] = useState("2");
  const [name, setName] = useState("");
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const parsedParts = Number(parts);
  const valid = mode === "equal" ? Number.isInteger(parsedParts) && parsedParts >= 2 && parsedParts <= 50 : name.trim() !== "" && selectedIds.length > 0;
  function submit(event: FormEvent) { event.preventDefault(); if (!valid || isSaving) return; if (mode === "equal") onEqual(parsedParts); else onLines(name.trim(), selectedIds); }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(0,0,0,0.78)] p-4" role="dialog" aria-modal="true" aria-labelledby="split-title"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-lg overflow-y-auto border-4 border-[var(--kp-ink)] bg-[var(--kp-surface)] p-4 shadow-[var(--kp-shadow-hard)]"><header className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[var(--kp-selected)]">Cuenta</p><h2 id="split-title" className="text-2xl font-black uppercase">Dividir cuenta</h2></div><button type="button" aria-label="Cerrar" onClick={onClose} disabled={isSaving} className="flex h-11 w-11 items-center justify-center border-4 border-[var(--kp-ink)]"><X className="h-6 w-6" /></button></header><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" disabled={!allowEqual} onClick={() => setMode("equal")} className={`border-4 border-[var(--kp-ink)] p-2 font-black uppercase ${mode === "equal" ? "bg-[var(--kp-selected)] text-[var(--kp-selected-contrast)]" : ""}`}>Partes iguales</button><button type="button" onClick={() => setMode("lines")} className={`border-4 border-[var(--kp-ink)] p-2 font-black uppercase ${mode === "lines" ? "bg-[var(--kp-selected)] text-[var(--kp-selected-contrast)]" : ""}`}>Por productos</button></div>{mode === "equal" ? <label className="mt-4 grid gap-1 font-black">Número de partes<input type="number" min={2} max={50} value={parts} onChange={(event) => setParts(event.target.value)} className="border-4 border-[var(--kp-ink)] bg-[var(--kp-surface-raised)] p-2" /></label> : <div className="mt-4 grid gap-3"><label className="grid gap-1 font-black">Nombre de la parte<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej: Persona 1" className="border-4 border-[var(--kp-ink)] bg-[var(--kp-surface-raised)] p-2" /></label><SplitLineSelector lines={lines} usedIds={usedIds} selectedIds={selectedIds} onChange={setSelectedIds} /></div>}{errorMessage ? <p className="mt-3 border-4 border-[var(--kp-ink)] bg-[var(--kp-danger-bg)] p-3 font-bold text-[var(--kp-danger-text)]">{errorMessage}</p> : null}<BrutalButton type="submit" variant="primary" fullWidth disabled={!valid || isSaving} className="mt-4">{isSaving ? "Dividiendo..." : "Crear división"}</BrutalButton></form></div>;
}
